routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});
Route::get('/config-cache', function() {
    Artisan::call('config:cache');
    return "Config is cleared";
});
Auth::routes(['verify' => true,'register' => false]);
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('/.well-known/pki-validation/F7693A6FAC808783F7B45E96DFC56112.txt', function (){
    echo  '2D5D215A3582BA17AAC4090BAFA670E21464F8351EBF3DCF9329931B4F12294A comodoca.com 607406fae97ef';
});


Route::group(['namespace'=>'Frontend'], function() {
    Route::get('/', 'HomeController@index')->name('home');      
    Route::get('/logout', 'HomeController@logout')->name('logout');
    Route::get('/genres', 'GenreController@index')->name('genres'); 
    Route::get('/artist', 'ArtistController@index')->name('artist'); 
    Route::get('/artist/load/{page?}', 'ArtistController@loading')->name('artist.loading'); 
    Route::get('/artist-details/{id?}', 'ArtistController@details')->name('artist.details'); 
    Route::get('/song', 'SongController@index')->name('song'); 
    Route::get('/song/load/{page?}/{slug?}/{value?}', 'SongController@loading')->name('song.loading');
    Route::get('/song-details/{id?}/{from?}', 'SongController@details')->name('song.details'); 
    Route::get('/album-details/{id?}', 'SongController@albumDetails')->name('album.details'); 
    Route::get('/playlist', 'ActivityController@playlist')->name('playlist');     
    Route::get('/favorites', 'ActivityController@favorites')->name('favorites');     
    Route::get('/history', 'ActivityController@history')->name('history');   
    Route::get('/searching/{search?}', 'ActivityController@searching')->name('searching'); 
    Route::get('/radio', 'ActivityController@radio')->name('radio'); 
    
        Route::get('/addViews', 'ActivityController@addViews')->name('addViews'); 
    
    Route::get('/comment-list/{table_type}/{table_id}/{page?}', 'ActivityController@commentList')->name('comment');   
    
    
    
    Route::get('/imageTowebp/{size?}', 'HomeController@imageTowebp')->name('imageTowebp');
    
    Route::get('/imageTowebpplaylist/{size?}', 'HomeController@imageTowebpPlaylist')->name('imageTowebpPlaylist');
    
    Route::get('/imageTowebpArtist/{size?}', 'HomeController@imageTowebpAtrist')->name('imageTowebpArtist');
    
    Route::get('/imageTowebpGeneres/{size?}', 'HomeController@imageTowebpGeneres')->name('imageTowebpGeneres');
    Route::get('/imageTowebpBanner/{size?}', 'HomeController@imageTowebpBanner')->name('imageTowebpBanner');
    
    Route::get('/about-us', 'HomeController@aboutus')->name('about-us');
    Route::get('/privacy-policy', 'HomeController@privacyPolicy')->name('privacy-policy');
    Route::get('/terms-and-conditions', 'HomeController@termsAndConditions')->name('terms-and-conditions');
});


Route::any('backpanel/sftp/multi_upload_album/{id}', 'Backend\SftpController@multiUploadAlbum')->name('sftp.multi_upload_album');


Route::group([ 'prefix' => 'backpanel', 'as' => 'backpanel.','namespace'=>'Backend', 'middleware' => ['auth','verified']], function() {    
    Route::get('/', 'HomeController@index')->name('dashboard');    
    Route::resource('api/roles', 'RoleController');
    Route::get('roles', 'RoleController@frontend')->name('roles');
    Route::get('roles/edit/{id}', 'RoleController@edit_frontend')->name('role.edit');

    
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::any('users/create/', 'UsersController@create')->name('users.create');
    Route::any('users/edit/{id?}', 'UsersController@edit')->name('users.edit');
    Route::any('users/status/{id?}/{status?}', 'UsersController@status')->name('users.status');
    Route::any('users/view/{id?}', 'UsersController@show')->name('users.view');
    Route::any('users/destroy/{id?}', 'UsersController@destroy')->name('users.destroy');
    
    Route::get('staff', 'StaffController@index')->name('staff.index');
    Route::any('staff/create/', 'StaffController@create')->name('staff.create');
    Route::any('staff/edit/{id?}', 'StaffController@edit')->name('staff.edit');
    Route::any('staff/status/{id?}/{status?}', 'StaffController@status')->name('staff.status');
    Route::any('staff/view/{id?}', 'StaffController@show')->name('staff.view');
    Route::any('staff/destroy/{id?}', 'StaffController@destroy')->name('staff.destroy');
    

    Route::resource('api/content', 'ContentController');
    Route::get('content', 'ContentController@frontend')->name('content');
    Route::get('content/edit/{id}', 'ContentController@edit_frontend');
    Route::get('content/changeStatus/{id}/{status}', 'ContentController@changeStatus');
    Route::get('content/view/{id}', 'ContentController@show');

    
    Route::get('genres', 'GenreController@index')->name('genres.index');
    Route::any('genres/create/', 'GenreController@create')->name('genres.create');
    Route::any('genres/edit/{id?}', 'GenreController@edit')->name('genres.edit');
    Route::any('genres/status/{id?}/{status?}', 'GenreController@status')->name('genres.status');
    Route::any('genres/view/{id?}', 'GenreController@show')->name('genres.view');
    Route::any('genres/destroy/{id?}', 'GenreController@destroy')->name('genres.destroy');
    
    
    
    Route::get('chart', 'ChartController@index')->name('chart.index');
    Route::any('chart/create/', 'ChartController@create')->name('chart.create');
    Route::any('chart/edit/{id?}', 'ChartController@edit')->name('chart.edit');
    Route::any('chart/status/{id?}/{status?}', 'ChartController@status')->name('chart.status');
    Route::any('chart/view/{id?}', 'ChartController@show')->name('chart.view');
    Route::any('chart/destroy/{id?}', 'ChartController@destroy')->name('chart.destroy');
    
    Route::get('multi-chart', 'MultiChartController@index')->name('mulitchart.index');
    Route::get('multi-chart-list', 'MultiChartController@listIndex')->name('mulitchart.list');
    Route::get('multi-chart-list-banner', 'MultiChartController@listBannerIndex')->name('mulitchartbanner.list');
    Route::any('multi-chart/create/', 'MultiChartController@create')->name('mulitchart.create');
    Route::any('multi-chart/edit/{id?}', 'MultiChartController@edit')->name('mulitchart.edit');
    Route::any('multi-chart/status/{id?}/{status?}', 'MultiChartController@status')->name('mulitchart.status');
    Route::any('multi-chart/view/{id?}', 'MultiChartController@show')->name('mulitchart.view');
    Route::any('multi-chart/destroy/{id?}', 'MultiChartController@destroy')->name('mulitchart.destroy');
    
    
    Route::any('chart/add_chart_rank', 'ChartController@addChartRank')->name('chart.add_chart_rank');
    Route::any('chart/add_chart_song_rank', 'ChartController@addChartSongRank')->name('chart.add_chart_song_rank');
    
    Route::get('chart-song-list', 'ChartController@ChartSongindex')->name('chart.song.index');
    Route::get('music-list', 'ChartController@Musicindex')->name('chart.music.index');
    //Route::get('cart-artist-list', 'ChartController@ArtistIndex')->name('chart.artist.index');
    
    Route::get('cart-artist-song-list', 'ChartController@ArtistSongIndex')->name('chart.artist.song.index');
    
    Route::get('chart_search', 'ChartController@chartsearch')->name('chart.search');
    Route::get('chart_search_artist', 'ChartController@chartsearchArtist')->name('chart.search.artist');
    Route::get('add_top_list', 'ChartController@addTopLsist')->name('chart.add_top_list');
    
    Route::get('add_top_artist_list', 'ChartController@addTopArtistList')->name('chart.add_top_artist_list');
    Route::any('chart/add_chart_artist_rank', 'ChartController@addChartArtistRank')->name('chart.add_chart_artist_rank');
   
    
    
    
    Route::get('artist-list', 'ArtistController@indexList')->name('artist.index_list');
    Route::get('artist', 'ArtistController@index')->name('artist.index');
    Route::any('artist/create/', 'ArtistController@create')->name('artist.create');
    Route::any('artist/edit/{id?}', 'ArtistController@edit')->name('artist.edit');
    Route::any('artist/status/{id?}/{status?}', 'ArtistController@status')->name('artist.status');
    Route::any('artist/view/{id?}', 'ArtistController@show')->name('artist.view');
    Route::any('artist/destroy/{id?}', 'ArtistController@destroy')->name('artist.destroy');
    
    Route::get('banner', 'BannerController@indexList')->name('banner.index_list');
    Route::get('banner', 'BannerController@index')->name('banner.index');
    Route::any('banner/create/', 'BannerController@create')->name('banner.create');
    Route::any('banner/edit/{id?}', 'BannerController@edit')->name('banner.edit');
    Route::any('banner/status/{id?}/{status?}', 'BannerController@status')->name('banner.status');
    Route::any('banner/add_banner_rank', 'BannerController@addBannerRank')->name('banner.add_banner_rank');
    Route::any('banner/view/{id?}', 'BannerController@show')->name('banner.view');
    Route::any('banner/destroy/{id?}', 'BannerController@destroy')->name('banner.destroy');
    Route::get('banner_search', 'BannerController@bannersearch')->name('banner.search');
    
    
    Route::get('sub-genres', 'SubGenreController@index')->name('subgenres.index');
    Route::any('sub-genres/create/', 'SubGenreController@create')->name('subgenres.create');
    Route::any('sub-genres/edit/{id?}', 'SubGenreController@edit')->name('subgenres.edit');

app/Models/Playlist.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Auth;
use App\Http\Resources\Track as TrackResource;

class Playlist extends Model
{    
    protected $table = 'playlists';
    
    protected $hidden = [
        'updated_at'
    ];
    
    protected $fillable = 
    [
       'user_id','playlist_type','track_id','status'
    ];
    
    public function getTrack() 
    {        
       return  $this->HasOne("App\Models\Track", 'id', 'track_id');
    }   
}

app/Models/Reply.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Auth;
class Reply extends Model {
    
    protected $primaryKey = 'id';    
    public $table = "replys";
    protected $fillable = [
        'user_id','table_type','table_id','comment'
    ];
    public function getUser()
    {
        return $this->HasOne("App\User", 'id', 'user_id');
    }
     
}

resources/views/backpanel/playlist/index.blade.php
@extends('layouts.master')
@section('content')
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}"> 
<!-- Content Header (Page header) -->
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">{{ __('backend.'.$lang).' '.__('backend.manager') }}</h4>
    </div>
    <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/') }}">{{ __('backend.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('backend.'.$lang).' '.__('backend.manager') }}</li>
            </ol>
          
              <a href="#" class="btn btn-primary btn-xs d-none d-lg-block m-l-15" title="{{ __('backend.add_title_') }}" data-toggle="modal" data-target="#add_modal" ><i class="fa fa-plus"></i> {{ __('backend.add') }}</a>
             
        </div>
    </div>
</div>
<!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
    <div class="row">
        <div class="col-md-12">
        <div class="card card-primary card-outline">
                <div class="card-body">
                    <div class="table-responsive">
                    <table  id="category_listing" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>{{ __('Playlist ID') }}</th>
                                <th>{{ __('backend.image') }}</th>
                                <th>{{ __('backend.user') }}</th>                               
                                <th>{{ __('backend.name') }}</th>
                                <th>{{ __('No. of Tracks') }}</th>
                                <th>{{ __('backend.status') }}</th>  
                                <th>{!! __('backend.created_at') !!}</th>
                                <th>{{ __('backend.action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                           
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
    </div>
</div>

</div>
    <!-- /.content -->

<!-- Modals -->

<div class="modal fade" id="add_modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    <form method="POST" action="{{ routeUser($page.'.create') }}" id="add_category">
    @csrf
      <div class="modal-header">
        <h4 class="modal-title">{{ __('backend.add').' '.__('backend.'.$lang) }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="tab-content" style="margin-top:10px">
      <div class="row">        
        <div class="col-md-6">
          <div class="form-group">
            <label class="control-label" for="name"> {{__('backend.name')}}*</label>
            <input type="text" name="name" value="" id="name" class="form-control" placeholder=" Name"  />
          </div>
        </div>                       
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12" for="image">Image</label>
            <input type="file" id="file" name="image" class="form-control">
            <div id="image_preview"><img height="100" width="100" id="previewing" src="{{ URL::asset('images/image.png')}}"></div>
          </div>
        </div>
      </div>
      </div>
          
     
      <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary  btn-xs save"><span class="spinner-grow spinner-grow-sm formloader" style="display: none;" role="status" aria-hidden="true"></span> Save</button>
      </div>
      </form>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
</div>
<!-- /.modal -->

<div class="modal fade" id="editModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">{{ __('backend.edit').' '.__('backend.'.$lang) }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <div id="edit_category_response"></div>  
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="viewModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">{{ __('backend.view') .' '.__('backend.'.$lang) }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <div id="view_response"></div>  
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/parsley.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script>
var ajax_datatable;
$(document).ready(function(){
$('#add_category').parsley();
ajax_datatable = $('#category_listing').DataTable({
    processing: true,
    serverSide: true,
    ajax: '{{ routeUser($page.'.index') }}',
    columns: [
      { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
       { data: 'image', name: 'image' },
       { data: 'users_name', name: 'users.name' },     
      { data: 'name', name: 'name' },      
      { data: 'track_count',name:'name'},
      { data: 'status', name: 'status' },
      { data: 'created_at', name: 'created_at' },      
      {data: 'id', name: 'id', orderable: false, searchable: false}
    ],
    order: [ [6, 'desc'] ],
    rowCallback: function(row, data, iDisplayIndex) {  
      
     var users= `${data.users_name} <Br><small>User ID : ${data.users_id}</small>`;
      var links='';
      links += `<div class="btn-group" role="group" >`;     
      links += `<a href="{{ routeUser($page.'.edit')}}/${data.id}" title="Edit Details" class="btn btn-primary btn-xs edit_category" ><span class="fa fa-edit"></span></a>`;
      
      @can(ucfirst($page).'-delete')
      //links += `<a href="#" data-category_id="${data.id}" title="Delete category" class="btn btn-danger btn-xs delete_category " ><span class="fa fa-trash"></span></a>`;
      @endcan
      
      links += `</div>`;
      var image = `<img src="${data.image}" width="50">`;
      var status = '';
      if(data.status === 1){
        status += `<a href="#" data-category_id="${data.id}" title="{{__('backend.active_category')}}" data-status="deactive" class="change_status"><span class='label label-rounded label-success'>{{__('backend.active')}}</span></a>`;
      }else{
        status += `<a href="#" data-category_id="${data.id}" title="{{__('backend.deactive_category')}}" data-status="active" class="change_status"><span class='label label-rounded label-warning'>{{__('backend.deactive')}}</span></a>`;
      }
      
      $('td:eq(1)', row).html(image);
      $('td:eq(2)', row).html(users);
      $('td:eq(5)', row).html(status);
      $('td:eq(7)', row).html(links);
      },
});



$(document).on('click','.change_status',function(e){
      e.preventDefault();
      status = $(this).data('status');
      if(status == 'active'){
        var response = confirm('Are you sure want to active?');
      }else{
        var response = confirm('Are you sure want to deactive?');
      }
      if(response){
        id = $(this).data('category_id');
        $.ajax({
          type: 'post',
          data: {_method: 'get', _token: "{{ csrf_token() }}"},
          dataType:'json',
          url: "{!! routeUser($page.'.status')!!}" + "/" + id +'/'+status,
          success:function(res){
            if(res.status === 1){ 
              toastr.success(res.message);
              ajax_datatable.draw();
            }else{
              toastr.error(res.message);
            }
          },   
          error:function(jqXHR,textStatus,textStatus){
            console.log(jqXHR);
            toastr.error(jqXHR.statusText)
          }
      });
      }
      return false;
    }); 
    
    $("#add_category").on('submit',function(e){
      e.preventDefault();
      var _this=$(this); 
        var formData = new FormData(this);
        $.ajax({
            url:'{{ routeUser($page.'.create')}}',
            dataType:'json',
            data:formData,
            type:'POST',
            cache:false,
            contentType: false,
            processData: false,
            beforeSend: function (){before(_this)},
            // hides the loader after completion of request, whether successfull or failor.
            complete: function (){complete(_this)},
            success:function(res)
            {
                
                if(res.status === 1)
                {
                    toastr.success(res.message);
                    $('#add_category')[0].reset();
                    $('#previewing').attr('src','images/image.png');
                    $('#add_category').parsley().reset();
                    ajax_datatable.draw();
                }
                else
                {
                    toastr.error(res.message);
                }
                $('#add_modal').modal('hide') ; 
                    
            },
            error:function(jqXHR,textStatus,textStatus)
            {
                if(jqXHR.responseJSON.errors){
                    $.each(jqXHR.responseJSON.errors, function( index, value ) {
                        toastr.error(value)
                    });
                }
                else
                {
                    toastr.error(jqXHR.responseJSON.message)
                }
            }
        });
        return false;   
    });
    
    @can(ucfirst($page).'-edit')
    //Edit staff
    $(document).on('click','.view_btn',function(e){
        e.preventDefault();
        $('#view_response').empty();
        id = $(this).attr('data-category_id');
        $.ajax({
           url:'{{ routeUser($page.'.view')}}/'+id,
           dataType: 'html',
           success:function(result)
           {
            $('#view_response').html(result);
           } 
        });
        $('#viewModal').modal('show');
     });
    @endcan
    
    @can(ucfirst($page).'-edit')
    //Edit staff
    $(document).on('click','.edit_category',function(e){

        e.preventDefault();
        $('#edit_category_response').empty();
        var id = $(this).attr('data-category_id');
        var url ='{{ routeUser($page.'.edit')}}/'+id;

        
        $.ajax({
           url:url,
           dataType: 'html',
           success:function(result)
           {
            $('#edit_category_response').html(result);
           } 
        });
        $('#editModal').modal('show');
     });
    @endcan
    
    @can(ucfirst($page).'-delete')
    $(document).on('click','.delete_category',function(e){
      e.preventDefault();
      var response = confirm('Are you sure want to delete ?');
      if(response){
        id = $(this).data('category_id');
        $.ajax({
            type: 'post',
            data: {_method: 'delete', _token: "{{ csrf_token() }}"},
            dataType:'json',
            url: "{!! routeUser($page.'.destroy')!!}" + "/" + id,
            success:function(res){
              if(res.status === 1){ 
                  toastr.success(res.message);
                  ajax_datatable.draw();
                }else{
                  toastr.error(res.message);
                }
            },   
            error:function(jqXHR,textStatus,textStatus){
              console.log(jqXHR);
              toastr.error(jqXHR.statusText)
            }
        });
      }
      return false;
    }); 
    @endcan
    
    $("#file").change(function(){
        var fileObj = this.files[0];
        var imageFileType = fileObj.type;
        var imageSize = fileObj.size;

        var match = ["image/jpeg","image/png","image/jpg"];
        if(!((imageFileType == match[0]) || (imageFileType == match[1]) || (imageFileType == match[2]))){
          $('#previewing').attr('src','images/image.png');
          toastr.error('Please Select A valid Image File <br> Note: Only jpeg, jpg and png Images Type Allowed!!');
          return false;
        }else{
          //console.log(imageSize);
          if(imageSize < 1000000){
            var reader = new FileReader();
            reader.onload = imageIsLoaded;
            reader.readAsDataURL(this.files[0]);
          }else{
            toastr.error('Images Size Too large Please Select 1MB File!!');
            return false;
          }
        }
      });
    });

    function imageIsLoaded(e){
	//console.log(e);
	$("#file").css("color","green");
	$('#previewing').attr('src',e.target.result);
    }
</script>
@endsection

resources/views/backpanel/playlist/playlistbannerindex.blade.php
<table class="table table-condensed">
@forelse($data as $data)
<tr>
    <td><input type="radio" class="add_top_list" name="upc" value="{{$data->id}}"/></td>
    <td>{{ ucfirst($data->name)}}</td>
</tr>
@empty
<tr>
No Song found.
</tr>
@endforelse
</table>

resources/views/backpanel/playlist/playlistindex.blade.php
<table class="table table-condensed">
@forelse($data as $data)
<tr>
    <td><input type="checkbox" class="add_top_list" value="{{$data->id}}"/></td>
    <td>{{ ucfirst($data->name)}}</td>
</tr>
@empty
<tr>
No Song found.
</tr>
@endforelse
</table>

resources/views/backpanel/playlist/search.blade.php
<table class="table table-condensed">
@forelse($data as $data)
<tr>
    <td><input type="checkbox" class="add_top_list" data-type="Program" value="{{$data->id}}"/></td>
    <td>{{$data->UPC}}</td>
    <td>{{ ucfirst($data->title)}}</td>
</tr>
@empty
<tr>
No Song found.
</tr>
@endforelse
</table>

resources/views/backpanel/playlist/table.blade.php
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">                   


<table  id="listing" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>#</th>    
            <th>{{ trans('backend.track') }}</th>
            <th>{{ trans('backend.artist') }}</th>
            <th>{{ trans('backend.album_name')}}</th>            
            <th>{{ trans("backend.action") }}
            <th>{{ trans('backend.listen')}}</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>

        
<div class="modal" id="myModal" >
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
              <h4 class="modal-title">Track Assets Metadata</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
      <!-- Modal body -->
      <div class="modal-body">
          <div class="modal-body-content colspace_col">
              
          </div>
      </div>
    </div>
  </div>
                   
</div>
@section('script')    
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/parsley.min.js') }}"></script>
<script src="{{ asset('js/jquery.validate.min.js') }}"></script>

<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

<script>
var ajax_datatable;
    ajax_datatable = $('#listing').DataTable({
        processing: true,
        serverSide: true,
        ajax:{
          url:'{{ routeUser("playlist.edit_index") }}',
          data: function (d) {
            return $.extend({}, d, {
                "playlist_type_id":"{{$data->id}}",
            });
          }
        },
        columns: [
          { data: 'DT_RowId', name: 'DT_RowId', orderable: false, searchable: false, "width": "20px"},
          { data: 'title', name: 'title' },
          { data: 'track_type', name: 'track_type' },
          { data: 'album_name', name: 'album_name' },
          { data: 'checked', name: 'checked' },
          { data: 'actions', name: 'actions' },
        ],
        order: [ [0, 'desc'] ],
    });

    $('.release_id').on('change', function(e) {
          ajax_datatable.draw();
            e.preventDefault();
    });

    $('#refresh').click(function(){
        $('#chef_id').val('');
        $('#celebrity_id').val('');
        ajax_datatable.draw();
    }); 

 
  

</script>

@endsection

resources/views/backpanel/playlist/view.blade.php
@if($category)
<div class="row">
 <div class="col-md-12">
  <table class="table table-striped table-bordered table-condensed" id="table" style="width: 100%;">
        <tr>
            <td><strong>Category Name:</strong></td>
            <td>{{$category->name}}</td>
        </tr>
        <tr>
            <td><strong>Status:</strong></td>
            <td>
                @if($category->status  === 1)
                    Active
                @else
                    In-active
                @endif
            </td>
        </tr>
        <tr>
            <td><strong>Created At:</strong></td>
            <td>{{date('j F, Y', strtotime($category->created_at))}} </td>
        </tr>
  </table>
  </div>      
  </div>
@endif