routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});
Route::get('/config-cache', function() {
    Artisan::call('config:cache');
    return "Config is cleared";
});
Auth::routes(['verify' => true,'register' => false]);
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('/.well-known/pki-validation/F7693A6FAC808783F7B45E96DFC56112.txt', function (){
    echo  '2D5D215A3582BA17AAC4090BAFA670E21464F8351EBF3DCF9329931B4F12294A comodoca.com 607406fae97ef';
});


Route::group(['namespace'=>'Frontend'], function() {
    Route::get('/', 'HomeController@index')->name('home');      
    Route::get('/logout', 'HomeController@logout')->name('logout');
    Route::get('/genres', 'GenreController@index')->name('genres'); 
    Route::get('/artist', 'ArtistController@index')->name('artist'); 
    Route::get('/artist/load/{page?}', 'ArtistController@loading')->name('artist.loading'); 
    Route::get('/artist-details/{id?}', 'ArtistController@details')->name('artist.details'); 
    Route::get('/song', 'SongController@index')->name('song'); 
    Route::get('/song/load/{page?}/{slug?}/{value?}', 'SongController@loading')->name('song.loading');
    Route::get('/song-details/{id?}/{from?}', 'SongController@details')->name('song.details'); 
    Route::get('/album-details/{id?}', 'SongController@albumDetails')->name('album.details'); 
    Route::get('/playlist', 'ActivityController@playlist')->name('playlist');     
    Route::get('/favorites', 'ActivityController@favorites')->name('favorites');     
    Route::get('/history', 'ActivityController@history')->name('history');   
    Route::get('/searching/{search?}', 'ActivityController@searching')->name('searching'); 
    Route::get('/radio', 'ActivityController@radio')->name('radio'); 
    
        Route::get('/addViews', 'ActivityController@addViews')->name('addViews'); 
    
    Route::get('/comment-list/{table_type}/{table_id}/{page?}', 'ActivityController@commentList')->name('comment');   
    
    
    
    Route::get('/imageTowebp/{size?}', 'HomeController@imageTowebp')->name('imageTowebp');
    
    Route::get('/imageTowebpplaylist/{size?}', 'HomeController@imageTowebpPlaylist')->name('imageTowebpPlaylist');
    
    Route::get('/imageTowebpArtist/{size?}', 'HomeController@imageTowebpAtrist')->name('imageTowebpArtist');
    
    Route::get('/imageTowebpGeneres/{size?}', 'HomeController@imageTowebpGeneres')->name('imageTowebpGeneres');
    Route::get('/imageTowebpBanner/{size?}', 'HomeController@imageTowebpBanner')->name('imageTowebpBanner');
    
    Route::get('/about-us', 'HomeController@aboutus')->name('about-us');
    Route::get('/privacy-policy', 'HomeController@privacyPolicy')->name('privacy-policy');
    Route::get('/terms-and-conditions', 'HomeController@termsAndConditions')->name('terms-and-conditions');
});


Route::any('backpanel/sftp/multi_upload_album/{id}', 'Backend\SftpController@multiUploadAlbum')->name('sftp.multi_upload_album');


Route::group([ 'prefix' => 'backpanel', 'as' => 'backpanel.','namespace'=>'Backend', 'middleware' => ['auth','verified']], function() {    
    Route::get('/', 'HomeController@index')->name('dashboard');    
    Route::resource('api/roles', 'RoleController');
    Route::get('roles', 'RoleController@frontend')->name('roles');
    Route::get('roles/edit/{id}', 'RoleController@edit_frontend')->name('role.edit');

    
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::any('users/create/', 'UsersController@create')->name('users.create');
    Route::any('users/edit/{id?}', 'UsersController@edit')->name('users.edit');
    Route::any('users/status/{id?}/{status?}', 'UsersController@status')->name('users.status');
    Route::any('users/view/{id?}', 'UsersController@show')->name('users.view');
    Route::any('users/destroy/{id?}', 'UsersController@destroy')->name('users.destroy');
    
    Route::get('staff', 'StaffController@index')->name('staff.index');
    Route::any('staff/create/', 'StaffController@create')->name('staff.create');
    Route::any('staff/edit/{id?}', 'StaffController@edit')->name('staff.edit');
    Route::any('staff/status/{id?}/{status?}', 'StaffController@status')->name('staff.status');
    Route::any('staff/view/{id?}', 'StaffController@show')->name('staff.view');
    Route::any('staff/destroy/{id?}', 'StaffController@destroy')->name('staff.destroy');
    

    Route::resource('api/content', 'ContentController');
    Route::get('content', 'ContentController@frontend')->name('content');
    Route::get('content/edit/{id}', 'ContentController@edit_frontend');
    Route::get('content/changeStatus/{id}/{status}', 'ContentController@changeStatus');
    Route::get('content/view/{id}', 'ContentController@show');

    
    Route::get('genres', 'GenreController@index')->name('genres.index');
    Route::any('genres/create/', 'GenreController@create')->name('genres.create');
    Route::any('genres/edit/{id?}', 'GenreController@edit')->name('genres.edit');
    Route::any('genres/status/{id?}/{status?}', 'GenreController@status')->name('genres.status');
    Route::any('genres/view/{id?}', 'GenreController@show')->name('genres.view');
    Route::any('genres/destroy/{id?}', 'GenreController@destroy')->name('genres.destroy');
    
    
    
    Route::get('chart', 'ChartController@index')->name('chart.index');
    Route::any('chart/create/', 'ChartController@create')->name('chart.create');
    Route::any('chart/edit/{id?}', 'ChartController@edit')->name('chart.edit');
    Route::any('chart/status/{id?}/{status?}', 'ChartController@status')->name('chart.status');
    Route::any('chart/view/{id?}', 'ChartController@show')->name('chart.view');
    Route::any('chart/destroy/{id?}', 'ChartController@destroy')->name('chart.destroy');
    
    Route::get('multi-chart', 'MultiChartController@index')->name('mulitchart.index');
    Route::get('multi-chart-list', 'MultiChartController@listIndex')->name('mulitchart.list');
    Route::get('multi-chart-list-banner', 'MultiChartController@listBannerIndex')->name('mulitchartbanner.list');
    Route::any('multi-chart/create/', 'MultiChartController@create')->name('mulitchart.create');
    Route::any('multi-chart/edit/{id?}', 'MultiChartController@edit')->name('mulitchart.edit');
    Route::any('multi-chart/status/{id?}/{status?}', 'MultiChartController@status')->name('mulitchart.status');
    Route::any('multi-chart/view/{id?}', 'MultiChartController@show')->name('mulitchart.view');
    Route::any('multi-chart/destroy/{id?}', 'MultiChartController@destroy')->name('mulitchart.destroy');
    
    
    Route::any('chart/add_chart_rank', 'ChartController@addChartRank')->name('chart.add_chart_rank');
    Route::any('chart/add_chart_song_rank', 'ChartController@addChartSongRank')->name('chart.add_chart_song_rank');
    
    Route::get('chart-song-list', 'ChartController@ChartSongindex')->name('chart.song.index');
    Route::get('music-list', 'ChartController@Musicindex')->name('chart.music.index');
    //Route::get('cart-artist-list', 'ChartController@ArtistIndex')->name('chart.artist.index');
    
    Route::get('cart-artist-song-list', 'ChartController@ArtistSongIndex')->name('chart.artist.song.index');
    
    Route::get('chart_search', 'ChartController@chartsearch')->name('chart.search');
    Route::get('chart_search_artist', 'ChartController@chartsearchArtist')->name('chart.search.artist');
    Route::get('add_top_list', 'ChartController@addTopLsist')->name('chart.add_top_list');
    
    Route::get('add_top_artist_list', 'ChartController@addTopArtistList')->name('chart.add_top_artist_list');
    Route::any('chart/add_chart_artist_rank', 'ChartController@addChartArtistRank')->name('chart.add_chart_artist_rank');
   
    
    
    
    Route::get('artist-list', 'ArtistController@indexList')->name('artist.index_list');
    Route::get('artist', 'ArtistController@index')->name('artist.index');
    Route::any('artist/create/', 'ArtistController@create')->name('artist.create');
    Route::any('artist/edit/{id?}', 'ArtistController@edit')->name('artist.edit');
    Route::any('artist/status/{id?}/{status?}', 'ArtistController@status')->name('artist.status');
    Route::any('artist/view/{id?}', 'ArtistController@show')->name('artist.view');
    Route::any('artist/destroy/{id?}', 'ArtistController@destroy')->name('artist.destroy');
    
    Route::get('banner', 'BannerController@indexList')->name('banner.index_list');
    Route::get('banner', 'BannerController@index')->name('banner.index');
    Route::any('banner/create/', 'BannerController@create')->name('banner.create');
    Route::any('banner/edit/{id?}', 'BannerController@edit')->name('banner.edit');
    Route::any('banner/status/{id?}/{status?}', 'BannerController@status')->name('banner.status');
    Route::any('banner/add_banner_rank', 'BannerController@addBannerRank')->name('banner.add_banner_rank');
    Route::any('banner/view/{id?}', 'BannerController@show')->name('banner.view');
    Route::any('banner/destroy/{id?}', 'BannerController@destroy')->name('banner.destroy');
    Route::get('banner_search', 'BannerController@bannersearch')->name('banner.search');
    
    
    Route::get('sub-genres', 'SubGenreController@index')->name('subgenres.index');
    Route::any('sub-genres/create/', 'SubGenreController@create')->name('subgenres.create');
    Route::any('sub-genres/edit/{id?}', 'SubGenreController@edit')->name('subgenres.edit');

app/Models/Views.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Auth;

class Views extends Model
{    
    protected $table = 'views';
    protected $fillable = [
        'table_type','table_id','user_id'
    ];

    protected $hidden = [
        'updated_at'
    ];
   
    public function getTrack() {
        return $this->HasOne("App\Models\Track", 'id', 'table_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;
use App\Models\Products;
use App\Models\UserDevice;
use App\Models\Media;
use App\Models\CelebrityCategory;
use App\Models\Country;

class User extends Authenticatable implements MustVerifyEmail, JWTSubject  {
	
    use Notifiable;
    use HasRoles;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
    protected  $appends = ['country'];
    protected $fillable = [
    	'id','name', 'email', 'password','type','first_name','last_name','gender','mobile','address','country_code','status','latitude','longitude','social_type','social_id','parent_chef_id'
    ];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
    protected $hidden = [
    	'password', 'remember_token',
    ];

	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array
	 */
    protected $casts = [
    	'email_verified_at' => 'datetime',
    ];

	/**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier() {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims() {
        return [];         
    }
	
	
    public function devices()
    {
        return $this->hasMany('App\Models\UserDevice','user_id');
    }
    public function getImageAttribute($value) 
    {
      return file_checker($value,'user');  
    }
    public function getCountryAttribute($value) 
    {
        $countryName=Country::select('name')->where(['phonecode'=>$this->country_code])->first();
            if($countryName){
                $countryName = $countryName->name;
            }
        return $countryName;
    }
}

resources/views/backpanel/video_old/edit.blade.php
@extends('admin.layouts.layout')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <section class="content-header1">
         @include('admin.partials.errors')
   </section>
   <!-- Content Header (Page header) -->
   <section class="content-header">
       
      <h1>
         {{ trans('admin_lang.'.$langPath)  }}
         <small>{{ trans("admin_lang.edit").' '.trans('admin_lang.'.$langPath)  }}</small>
      </h1>
      <ol class="breadcrumb">
         <li><a href="{!! userUrl('dashboard') !!}"><i class="fa fa-dashboard"></i> {{ trans("admin_lang.home") }}</a></li>
         <li class="active"><a href="{!! routeUser($pagePath.'.index') !!}">{{ trans("admin_lang.".$langPath)  }}</a></li>
         <li class="active"> {{ trans("admin_lang.edit").' '.trans('admin_lang.'.$langPath) }}</li>
      </ol>
   </section>
   <!-- Main content -->
   <section class="content">
      <!-- Info boxes -->
      <div class="row">
         <div class="col-xs-12">
            <div class="box">
               <div class="box-header">
                  <!-- <h3 class="box-title">Hover Data Table</h3> -->
               </div>
               <!-- /.box-header -->
               <div class="box-body">
                  {!! Form::model($sdata,  ['route'=>[routeFormUser($pagePath.'.update'),encrypt($sdata->id),$type], 'method'=>'post','files'=>true,'class'=>'upload_submit']) !!}
                  @include('admin.'.$pagePath.'.form')
                  {{ Form::close() }}
               </div>
               <!-- /.box-body -->
            </div>
            <!-- /.box -->
         </div>
      </div>
      <!-- /.row -->
   </section>
   <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/backpanel/video_old/edit_assets.blade.php
<div class="row">
    <div class="col-sm-12">
           <div class="col-md-4">
                             

                        <a class="btn btn-social btn-primary add_track" href="#">
                        <i class="fa fa-plus"></i> {{ trans('admin_lang.add').' '.trans('admin_lang.track') }}
                        </a>
                         </div>
        
               <div class="modal" id="myModal" >
  <div class="modal-dialog" style="width: 750px;">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
          <div class="row">
              <div class="col-md-8"> <h4 class="modal-title">Assets Metadata</h4></div>
              <div class="col-md-4"> <button type="button" class="close pull-right" data-dismiss="modal">&times;</button></div>
          </div>
       
      </div>
      <!-- Modal body -->
      <div class="modal-body">
          <div class="modal-body-content colspace_col">
              
          </div>
      </div>
    </div>
  </div>
</div>
       <br/><br/><br/>
         <div class="box-body">
                  
                  <table id="userTable" class="table table-bordered table-hover datatable">
                     <thead>
                        <tr>
                           <th class="action">#</th>                 
                           <th class="action">{{ trans('admin_lang.track') }}</th>
                           <th class="action">{{ trans('admin_lang.type')}}</th>
                           <th class="action" width="110px">{{ trans("admin_lang.action") }}
                           </th>
                        </tr>
                     </thead>
                     <tfoot>
                        <tr>
                           <th>#</th>
                           <th>{{ trans('admin_lang.track')}}</th>
                           <th>{{ trans('admin_lang.type')}}</th>
                           <th>{{ trans("admin_lang.action") }}</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
   </div>
</div>
<script>
$(document).ready(function(){
    var table = $('#userTable').DataTable({
           "bProcessing": true,
           "serverSide": true,
           "pageLength": 100,
           "searching": false,
           "order": [[0, "asc"]],
           "bPaginate": false,
           "ajax": {
               url: "{{ routeUser('track.index',['id'=>$sdata->id]) }}",
               data: function (d) {
                    return $.extend({}, d, {
                        "start_date": $('.sdate').val(),
                        "end_date": $('.edate').val(),
                    });
                },
               error: function () {
                   alert("{{trans('admin_lang.something_went_wrong')}}");
               }
           },
          
           "aoColumns": [
               {mData: 'DT_RowId'},
               {mData: 'title'},
               {mData: 'track_type'},
               {mData: 'actions'}
           ],
           "aoColumnDefs": [
               {"bSortable": false, "aTargets": ['action']}
           ],
            language: {
            searchPlaceholder: "Search"
        },
       });
       
       
        $('.filter').click(function (e) {
            table.ajax.reload();
        });
        
        $('.add_track').click(function(){
            $(".loding_img").show();
            var id = '{{encrypt($sdata->id)}}';
            var type = '{{$type}}';
            $.ajax({
                 url: "{{routeUser('track.create')}}",
                 type: 'get',
                 data:{'id':id,'type':type,'form_type':'store'},
                 success: function (data) 
                 {
                    $('#myModal').modal('show');
                    $(".loding_img").hide();
                    $('.modal-body-content').html(data);
                 },               
             });
        });
        
        $(document).on('click','.edit_track',function(){ 
        var url = $(this).data('href_url');
        $(".loding_img").show();
            $.ajax({
                 url: url,
                 type: 'get',
                 data:{'form_type':'update'},
                 success: function (data) 
                 {
                    $('#myModal').modal('show');
                    $(".loding_img").hide();
                    $('.modal-body-content').html(data);
                 },               
             });
        });
        
        
        
        
        $(document).on('click','.form_submit_track',function(){
            $(".upload_submit_track").validate({
                highlight: function(element) {
                    $(element).closest('.form-group').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-error');
                },		
                rules: {
                    title: "required",
                    'primary_artist[]': "required",
                    'author[]': "required",
                    'composer[]': "required",
                    genre_id: "required",				
                    label_id: "required",				
                    format: "required",				
                    original_release_date: "required",				
                    p_line: "required",				
                    c_line: "required",				
                    production_year: "required",
                    UPC: "required",
                    //price_id: "required",
                    title_language: "required",
                    lyrics_language: "required",
                    ISRC: "required",
		},
		messages: {
                    title: "The title field is required.",
                    'primary_artist[]': "The primary artist field is required.",
                    'author[]': "The author field is required.",
                    'composer[]': "The composer field is required.",
                    genre_id: "The genre field is required.",				
                    label_id: "The label field is required.",				
                    format: "The format field is required.",				
                    original_release_date: "The Physical/Original release date field is required.",				
                    p_line: "The  ℗ line field is required.",				
                    c_line: "The &copy; line  field is required.",				
                    production_year: "The production year  field is required.",				
                    UPC: "The UPC/EAN  field is required.",
                    //price_id: "The main price tier field is required.",
                    title_language: "The title language field is required.",
                    lyrics_language: "The lyrics language field is required.",
                    ISRC: "The ISRC field is required.",
		}
            });
            if ($('.upload_submit_track').valid()) {
                $(".loding_img").show();
                var route_url =  $("input[name=route_url]").val();
                var track_id_main =  $("input[name=track_id_main]").val();
                var track_type =  $("input[name=track_type]").val();
                var secondary_track_type =  $("input[name=secondary_track_type]:checked").val();
                var instrumental =  $("input[name=instrumental]:checked").val();
                var title =  $("input[name=title]").val();
                var subtitle =  $("input[name=subtitle]").val();
                var publisher =  $("input[name=publisher]").val();
                var p_line =  $("input[name=p_line]").val();
                var ISRC =  $("input[name=ISRC]").val();
                var producer_catalogue_number =  $("input[name=producer_catalogue_number]").val();
                var track_for_the_release =  $("input[name=track_for_the_release]:checked").val();
                var parental_advisory =  $("input[name=parental_advisory]:checked").val();
                var track_lyrics =  $("input[name=track_lyrics]").val();
                var preview_start =  $("input[name=preview_start]").val();

                var production_year =  $(".production_year option:selected").val();
                var genre_id =  $(".genre_id option:selected").val();
                var subgenre_id =  $(".subgenre_id option:selected").val();
                var price_id =  $(".price_id option:selected").val();
                var lyrics_language =  $(".lyrics_language option:selected").val();
                var title_language =  $(".title_language option:selected").val();



                var primary_artist = [] ;
                $(".primary_artist").each(function(i){
                    primary_artist[i] = $(this).val();
                });

                var featuring_artist = [] ;
                $(".featuring_artist").each(function(i){
                    featuring_artist[i] = $(this).val();
                });
                var remixer = [] ;
                $(".remixer").each(function(i){
                    remixer[i] = $(this).val();
                });
                var author = [] ;
                $(".author").each(function(i){
                    author[i] = $(this).val();
                });
                var composer = [] ;
                $(".composer").each(function(i){
                    composer[i] = $(this).val();
                });
                var arranger = [] ;
                $(".arranger").each(function(i){
                    arranger[i] = $(this).val();
                });
                var producer = [] ;
                $(".producer").each(function(i){
                    producer[i] = $(this).val();
                });


                var form_data = {
                   'route_url':route_url,
                   'track_id_main':track_id_main,
                   'track_type':track_type,
                   'secondary_track_type':secondary_track_type,
                   'instrumental':instrumental,
                   'title':title,
                   'subtitle':subtitle,
                   'primary_artist':primary_artist,
                   'featuring_artist':featuring_artist,
                   'remixer':remixer,
                   'author':author,
                   'composer':composer,
                   'arranger':arranger,
                   'producer':producer,
                   'p_line':p_line,
                   'production_year':production_year,
                   'publisher':publisher,              
                   'ISRC':ISRC,
                   'genre_id':genre_id,
                   'subgenre_id':subgenre_id,
                   'track_for_the_release':track_for_the_release,
                   'price_id':price_id,
                   'producer_catalogue_number':producer_catalogue_number,                                         
                   'parental_advisory':parental_advisory,
                   'preview_start':preview_start, 
                   'title_language':title_language,
                   'track_lyrics':track_lyrics, 
                   'lyrics_language':lyrics_language,              
                };                
                
                $.ajax({
                    url:route_url,
                    type: 'post',
                    data: {
                        '_token': '{{ csrf_token() }}',
                        'form_data':form_data,                        
                    },
                    dataType:'JSON',
                    success: function (data) 
                    {
                         $(".loding_img").hide();
                         $('#myModal').modal('hide');
                        if(data.status==false)
                        {
                            $('.content-header1').html('<div class="alert alert-danger"><strong>Danger!</strong> '+data.message+'</div>')
                        }
                    else{
                         
                         table.ajax.reload();
                        $('.content-header1').html('<div class="alert alert-success"><strong>Success!</strong> '+data.success+'</div>');                
                        }
                    }
                    
                });
            }
        });                
        });
</script>

resources/views/backpanel/video_old/price_tire.blade.php
<div class="row colspace_col">
    <div class="col-sm-6">
       <div class="form-group  @if ($errors->has('format')) has-error @endif">
            <label for="format" class="control-label required">{{ trans("admin_lang.choose_price_tire") }}</label>$9.99
            {{-- Form::select('price_id',$price,null,['class'=>'form-control price_id','placeholder'=> ucwords(trans("admin_lang.choose_price_tire")),'style'=>'text-transform: capitalize;']) --}}
             @if ($errors->has('price_id'))<span class="error">{{ $errors->first('price_id') }}</span>@endif
        </div>
   </div>
</div>
<script>
$(document).ready(function(){
   $('.price_id').change(function(){
      $('.upload_submit').submit(); 
   }); 
});
</script>

resources/views/backpanel/video_old/store.blade.php
<div class="row">
    <div class="col-sm-12 " style="font-size: 20px; text-align: right; display: none;">
        <span><input class="selectallstore" name="selectallstore" type="checkbox"></span>
        <span>Select All</span>
    </div>
        @forelse($store as $store)
            <div class="col-sm-2">
                <div class="boxsetup" style="    border: 1px solid #ccc;    margin: 5px;height: 180px;padding: 15px;text-align: center;box-shadow: 0px 0px 0px 5px aliceblue;">
                <img src="{{asset($store->getStore->image)}}" style="width:100%;"><br/>
                <span>{{ Form::checkbox('store',$store->id,($store->status==0)?false:true,['class'=>'setstore','data-release_id'=>$store->release_id])}}</span>
                <span>{{$store->getStore->title}}</span>
            </div>
            </div>
        @empty
        @endforelse
    
</div>


<script>
$(document).on('click','.setstore',function(){
   var status = 0;
   if($(this).is(':checked')){
     status = 1;
   }else{
     status = 0;
   }
   var id =  $(this).val();
   var release_id = $(this).data('release_id');
   $(".loding_img").show();
      $.ajax({
          url: "{{ routeUser('ajax.video.store.set') }}",
          type: 'get',
          data:{status:status,id:id,release_id:release_id},
          success: function (data)
          {
            $(".loding_img").hide();
            validateSelectAll();
          }
      });
});

$(document).on('click','.selectallstore',function(){
   var status = 0;
   if($(this).is(':checked')){
     status = 1;
     $(".setstore").prop('checked', true);
   }else{
     status = 0;
     $(".setstore").prop('checked', false);
   }
   var release_id = '{{ app('request')->input('id') }}';   
   $(".loding_img").show();
      $.ajax({
          url: "{{ routeUser('ajax.video.store.selectall') }}",
          type: 'get',
          data:{status:status,release_id:release_id},
          success: function (data)
          {
            $(".loding_img").hide();
          }
      });
});

$(document).ready(function(){
  validateSelectAll();
});

function validateSelectAll(){
  var totcheckbox = $('.setstore').length;
  var selectcheckbox = $('.setstore:checked').length;
  if(totcheckbox==selectcheckbox){
    $(".selectallstore").prop('checked', true);
  }
  else{
    $(".selectallstore").prop('checked', false);
  }
}
</script>